var str = '';
str += "    <div id=\"component-data\" class=\"container-fluid\">";
str += "        <div class=\"row\">";
str += "            <div class=\"col-md-12\">";
str += "                <div class =\"form-input\">";
str += "                  <div class=\"card\">";
str += "                      <div class=\"card-content\">";
str += "                          <h4 class=\"card-title\">Add Branch<\/h4>";
str += "                          <form id=\"main-form\" class=\"form-horizontal\">";
str += "                            <div class=\"row\">";
str += "                              <div class=\"col-md-6\">";
str += "                                <div class=\"row\">";
str += "                                    <label class=\"col-md-4 label-on-left\">Branch Name<\/label>";
str += "                                    <div class=\"col-md-8\">";
str += "                                        <div class=\"form-group label-floating is-empty\">";
str += "                                            <label class=\"control-label\"><\/label>";
str += "                                            <input type=\"text\" id=\"branch-name\" class=\"form-control\">";
str += "                                        <\/div>";
str += "                                    <\/div>";
str += "                                <\/div><!--row-->";
str += "                                <div class=\"row\">";
str += "                                    <label class=\"col-md-4 label-on-left\">Branch Address<\/label>";
str += "                                    <div class=\"col-md-8\">";
str += "                                        <div class=\"form-group label-floating is-empty\">";
str += "                                            <label class=\"control-label\"><\/label>";
str += "                                            <textarea name=\"baddress\" id=\"branch-address\" class=\"form-control\" rows=\"3\" cols=\"80\"><\/textarea>";
str += "                                        <\/div>";
str += "                                    <\/div>";
str += "                                <\/div><!-- row-->";
str += "                              <\/div>";
str += "                              <div class=\"col-md-6\">";
str += "                                <div class=\"row\">";
str += "                                    <label class=\"col-md-3 label-on-left\">Branch Code<\/label>";
str += "                                    <div class=\"col-md-9\">";
str += "                                        <div class=\"form-group label-floating is-empty\">";
str += "                                            <label class=\"control-label\"><\/label>";
str += "                                            <input type=\"text\" id=\"branch-code\" class=\"form-control\">";
str += "                                        <\/div>";
str += "                                    <\/div>";
str += "                                <\/div>";
str += "                              <\/div>";
str += "                            <\/div><!--row -->";
str += "                              <div class=\"row\">";
str += "                                  <div class=\"col-md-12\" style = \"text-align:center;margin-top:30px\">";
str += "                                      <div class=\"form-group form-button\">";
str += "                                        <button type=\"button\" class=\"btn btn-fill btn-success\" id=\"sp-save-btn\">Add Branch<\/button>";
str += "                                        <button type=\"reset\" class=\"btn btn-fill btn-danger\"><i class=\"material-icons\">delete_forever<\/i> Cancel<\/button>";
str += "                                      <\/div>";
str += "                                  <\/div>";
str += "                              <\/div>";
str += "                          <\/form>";
str += "                      <\/div>";
str += "                  <\/div><!-- card-->";
str += "                <\/div><!-- from-input -->";
str += "                <div class=\"card\">";
str += "                    <div class=\"card-content\">";
str += "                      <div class= \"toolbar pull-right\">";
str += "                        <a href=\"javascript:;\" id=\"refresh\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Tooltip on top\"><i class=\"material-icons\">refresh<\/i><\/a>";
str += "                      <\/div>";
str += "                        <h4 class=\"card-title\">Branch Setup<\/h4>";
str += "                        <div class=\"material-datatables\">";
str += "                            <table id=\"datatables-branch\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">";
str += "                                <thead>";
str += "                                    <tr>";
str += "                                        <th>Branch Name<\/th>";
str += "                                        <th>Branch Code<\/th>";
str += "                                        <th>Status<\/th>";
str += "                                        <th class=\"disabled-sorting text-right\">Actions<\/th>";
str += "                                    <\/tr>";
str += "                                <\/thead>";
str += "                                <tbody id = \"table-body\">";
str += "";
var BRANCH_TOP = str;
var str = '';
str += "                                <\/tbody>";
str += "                            <\/table>";
str += "                        <\/div>";
str += "                    <\/div>";
str += "                    <!-- end content-->";
str += "                <\/div>";
str += "                <!--  end card  -->";
str += "";
str += "            <\/div>";
str += "            <!-- end col-md-12 -->";
str += "        <\/div>";
str += "        <!-- end row -->";
str += "    <\/div>";
str += "<\/div>";
str += "";
var BRANCH_BOTTOM = str;


// Denomination Section
var DENOMINATION_TOP="";
DENOMINATION_TOP += "<div id=\"component-data\" class=\"container-fluid\">";
DENOMINATION_TOP += "    <div class=\"row\">";
DENOMINATION_TOP += "        <div class=\"col-md-12\">";
DENOMINATION_TOP += "            <div class =\"form-input\">";
DENOMINATION_TOP += "              <div class=\"card\">";
DENOMINATION_TOP += "                  <div class=\"card-content\">";
DENOMINATION_TOP += "                      <h4 class=\"card-title\">Add Denomination<\/h4>";
DENOMINATION_TOP += "                      <form class=\"form-horizontal\">";
DENOMINATION_TOP += "                        <div class=\"row\">";
DENOMINATION_TOP += "                          <div class=\"col-md-6\">";
DENOMINATION_TOP += "                            <div class=\"row\">";
DENOMINATION_TOP += "                                <label class=\"col-md-4 label-on-left\">Denomination Unit<\/label>";
DENOMINATION_TOP += "                                <div class=\"col-md-8\">";
DENOMINATION_TOP += "                                    <div class=\"form-group label-floating is-empty\">";
DENOMINATION_TOP += "                                        <label class=\"control-label\"><\/label>";
DENOMINATION_TOP += "                                        <input type=\"number\" id=\"denomination-unit\" class=\"form-control\">";
DENOMINATION_TOP += "                                    <\/div>";
DENOMINATION_TOP += "                                <\/div>";
DENOMINATION_TOP += "                            <\/div><!--row-->";
DENOMINATION_TOP += "                          <\/div>";
DENOMINATION_TOP += "                        <\/div><!--row -->";
DENOMINATION_TOP += "                          <div class=\"row\">";
DENOMINATION_TOP += "                              <div class=\"col-md-12\" style = \"text-align:center;margin-top:30px\">";
DENOMINATION_TOP += "                                  <div class=\"form-group form-button\">";
DENOMINATION_TOP += "                                    <button type=\"button\" class=\"btn btn-fill btn-success sp-save-btn\"><span class=\"loader\"><img src=\"img\/loader.gif\"><\/span><span class=\"button-text\"><i class=\"material-icons\">save<\/i> Add Denomination<\/span><\/button>";
DENOMINATION_TOP += "                                    <button type=\"reset\" class=\"btn btn-fill btn-danger\"><i class=\"material-icons\">delete_forever<\/i> Cancel<\/button>";
DENOMINATION_TOP += "                                  <\/div>";
DENOMINATION_TOP += "                              <\/div>";
DENOMINATION_TOP += "                          <\/div>";
DENOMINATION_TOP += "                      <\/form>";
DENOMINATION_TOP += "                  <\/div>";
DENOMINATION_TOP += "              <\/div><!-- card-->";
DENOMINATION_TOP += "            <\/div><!-- from-input -->";
DENOMINATION_TOP += "            <div class=\"card\">";
DENOMINATION_TOP += "                <div class=\"card-content\">";
DENOMINATION_TOP += "                  <div class= \"toolbar pull-right\">";
DENOMINATION_TOP += "                    <a href=\"javascript:;\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Tooltip on top\" onclick=\"demo.showNotification('top','right','Refresh Successful!')\"><i class=\"material-icons\">refresh<\/i><\/a>";
DENOMINATION_TOP += "                  <\/div>";
DENOMINATION_TOP += "                    <h4 class=\"card-title\">Denomination<\/h4>";
DENOMINATION_TOP += "                    <div class=\"material-datatables\">";
DENOMINATION_TOP += "                        <table id=\"datatables-denominations\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">";
DENOMINATION_TOP += "                            <thead>";
DENOMINATION_TOP += "                                <tr>";
DENOMINATION_TOP += "                                    <th>Unit<\/th>";
DENOMINATION_TOP += "                                    <th class=\"disabled-sorting text-right\">Actions<\/th>";
DENOMINATION_TOP += "                                <\/tr>";
DENOMINATION_TOP += "                            <\/thead>";
DENOMINATION_TOP += "                            <tbody id = \"table-body\">";

var DENOMINATION_BOTTOM="";
DENOMINATION_BOTTOM += "                            <\/tbody>";
DENOMINATION_BOTTOM += "                        <\/table>";
DENOMINATION_BOTTOM += "                    <\/div>";
DENOMINATION_BOTTOM += "                <\/div>";
DENOMINATION_BOTTOM += "                <!-- end content-->";
DENOMINATION_BOTTOM += "            <\/div>";
DENOMINATION_BOTTOM += "            <!--  end card  -->";
DENOMINATION_BOTTOM += "";
DENOMINATION_BOTTOM += "        <\/div>";
DENOMINATION_BOTTOM += "        <!-- end col-md-12 -->";
DENOMINATION_BOTTOM += "    <\/div>";
DENOMINATION_BOTTOM += "    <!-- end row -->";
DENOMINATION_BOTTOM += "<\/div>";
DENOMINATION_BOTTOM += "";


var USER_TOP="";
USER_TOP += "<div class=\"container-fluid\">";
USER_TOP += "                    <div class=\"row\">";
USER_TOP += "                        <div class=\"col-md-12\">";
USER_TOP += "                            <div class =\"form-input\">";
USER_TOP += "                              <div class=\"card\">";
USER_TOP += "                                  <div class=\"card-content\">";
USER_TOP += "                                      <h4 class=\"card-title\">Add User<\/h4>";
USER_TOP += "                                      <form class=\"form-horizontal\">";
USER_TOP += "                                        <div class=\"row\">";
USER_TOP += "                                          <div class=\"col-md-6\">";
USER_TOP += "                                            <div class=\"row\">";
USER_TOP += "                                                <label class=\"col-md-4 label-on-left\">User Name<\/label>";
USER_TOP += "                                                <div class=\"col-md-8\">";
USER_TOP += "                                                    <div class=\"form-group label-floating is-empty\">";
USER_TOP += "                                                        <label class=\"control-label\"><\/label>";
USER_TOP += "                                                        <input type=\"text\" class=\"form-control\">";
USER_TOP += "                                                    <\/div>";
USER_TOP += "                                                <\/div>";
USER_TOP += "                                            <\/div><!--row-->";
USER_TOP += "                                            <div class=\"row\">";
USER_TOP += "                                                <label class=\"col-md-4 label-on-left\">Expiry Date<\/label>";
USER_TOP += "                                                <div class=\"col-md-8\">";
USER_TOP += "                                                    <div class=\"form-group label-floating is-empty\">";
USER_TOP += "                                                        <label class=\"control-label\"><\/label>";
USER_TOP += "                                                        <input type=\"text\" class=\"form-control\">";
USER_TOP += "                                                    <\/div>";
USER_TOP += "                                                <\/div>";
USER_TOP += "                                            <\/div><!-- row-->";
USER_TOP += "                                          <\/div>";
USER_TOP += "                                          <div class=\"col-md-6\">";
USER_TOP += "                                            <div class=\"row\">";
USER_TOP += "                                                <label class=\"col-md-3 label-on-left\">Branch Code<\/label>";
USER_TOP += "                                                <div class=\"col-md-9\">";
USER_TOP += "                                                    <div class=\"form-group label-floating is-empty\">";
USER_TOP += "                                                        <label class=\"control-label\"><\/label>";
USER_TOP += "                                                        <input type=\"text\" class=\"form-control\">";
USER_TOP += "                                                    <\/div>";
USER_TOP += "                                                <\/div>";
USER_TOP += "                                            <\/div>";
USER_TOP += "                                          <\/div>";
USER_TOP += "                                        <\/div><!--row -->";
USER_TOP += "                                          <div class=\"row\">";
USER_TOP += "                                              <div class=\"col-md-12\" style = \"text-align:center;margin-top:30px\">";
USER_TOP += "                                                  <div class=\"form-group form-button\">";
USER_TOP += "                                                    <button type=\"button\" class=\"btn btn-fill btn-success sp-save-btn\"><i class=\"material-icons\">save<\/i> Add User<\/button>";
USER_TOP += "                                                    <button type=\"reset\" class=\"btn btn-fill btn-danger\"><i class=\"material-icons\">delete_forever<\/i> Cancel<\/button>";
USER_TOP += "                                                  <\/div>";
USER_TOP += "                                              <\/div>";
USER_TOP += "                                          <\/div>";
USER_TOP += "                                      <\/form>";
USER_TOP += "                                  <\/div>";
USER_TOP += "                              <\/div><!-- card-->";
USER_TOP += "                            <\/div><!-- from-input -->";
USER_TOP += "                            <div class=\"card\">";
USER_TOP += "                                <div class=\"card-content\">";
USER_TOP += "                                  <div class= \"toolbar pull-right\">";
USER_TOP += "                                    <a href=\"javascript:;\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Tooltip on top\" onclick=\"demo.showNotification('top','right','Refresh Successful!')\"><i class=\"material-icons\">refresh<\/i><\/a>";
USER_TOP += "                                  <\/div>";
USER_TOP += "                                    <h4 class=\"card-title\">User Setup<\/h4>";
USER_TOP += "                                    <div class=\"material-datatables\">";
USER_TOP += "                                        <table id=\"datatables-user\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">";
USER_TOP += "                                            <thead>";
USER_TOP += "                                                <tr>";
USER_TOP += "                                                    <th>User Name<\/th>";
USER_TOP += "                                                    <th>Expiry Date<\/th>";
USER_TOP += "                                                    <th>Branch Code<\/th>";
USER_TOP += "                                                    <th>Status<\/th>";
USER_TOP += "                                                    <th class=\"disabled-sorting text-right\">Actions<\/th>";
USER_TOP += "                                                <\/tr>";
USER_TOP += "                                            <\/thead>";
USER_TOP += "                                            <tbody>";
var USER_BOTTOM="";
USER_BOTTOM += "<\/tbody>";
USER_BOTTOM += "                                        <\/table>";
USER_BOTTOM += "                                    <\/div>";
USER_BOTTOM += "                                <\/div>";
USER_BOTTOM += "                                <!-- end content-->";
USER_BOTTOM += "                            <\/div>";
USER_BOTTOM += "                            <!--  end card  -->";
USER_BOTTOM += "";
USER_BOTTOM += "                        <\/div>";
USER_BOTTOM += "                        <!-- end col-md-12 -->";
USER_BOTTOM += "                    <\/div>";
USER_BOTTOM += "                    <!-- end row -->";
USER_BOTTOM += "                <\/div>";
